/**
 * RxNorm ingredient name lookup from a pre-built JSON table.
 *
 * The table is generated by scripts/build-rxnorm-lookup.mjs from the
 * standalone RxNorm Full Release (SAB=RXNORM, TTY=IN entries only).
 *
 * RxNorm core vocabulary is a US federal government product in the public
 * domain. Required attribution:
 *   "This product uses publicly available data courtesy of the U.S. National
 *    Library of Medicine (NLM), National Institutes of Health, Department of
 *    Health and Human Services; NLM is not responsible for the product and
 *    does not endorse or recommend this or any other product."
 *
 * If the data file is absent or empty (e.g. a fresh clone before running the
 * build script), all lookups return undefined gracefully — the converter
 * continues to work, just without resolved medication names.
 */

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';

let _cache: Record<string, string> | null = null;

function getCache(): Record<string, string> {
  if (_cache !== null) return _cache;
  try {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = dirname(__filename);
    // Resolves to dist/data/rxnorm-names.json at runtime (copied during build)
    const dataPath = join(__dirname, '../../data/rxnorm-names.json');
    _cache = JSON.parse(readFileSync(dataPath, 'utf-8')) as Record<string, string>;
  } catch {
    _cache = {};
  }
  return _cache;
}

/**
 * Look up a generic ingredient name by RxNorm RXCUI.
 * Returns undefined if the code is not in the lookup table.
 */
export function lookupRxNormName(rxcui: string): string | undefined {
  return getCache()[rxcui];
}
