/**
 * Command descriptors DERIVED from the live commander registry.
 *
 * `cascade capabilities` is the discovery surface an AI agent reads to learn
 * what this CLI can do — cascade-agent splices its raw output into the system
 * prompt verbatim. Anything missing from it does not exist as far as the agent
 * is concerned, and anything invented is a tool the agent will try to call and
 * cannot reach.
 *
 * It was previously a hand-written list, and the list drifted: 12 of 34
 * invocable commands described, every write and recovery verb invisible, and an
 * MCP tool advertised that was never implemented. So the descriptors here are
 * GENERATED by walking the registry that `cascade` actually parses with. A
 * command that is registered is described by construction; there is no list to
 * forget to update.
 *
 * Prose that generation cannot know — examples, output schemas, the safety
 * semantics of a destructive verb — comes from the enrichment table in
 * `./enrichment.js`, which can only DECORATE a command discovered here. See the
 * comment at the top of that file for why that direction is load-bearing.
 */

import type { Command, Option, Argument } from 'commander';

/** One argument or option of a command, in the shape agents already consume. */
export interface CommandParameter {
  /** Argument name (`pod-dir`) or option long flag (`--dry-run`). */
  name: string;
  /** `string`, `string[]` for a variadic argument, or `boolean` for a flag. */
  type: string;
  /**
   * Present, and always `true`, only when the CLI enforces the parameter.
   * Omitted when optional — see `PARAMETER_CONVENTIONS`, which states that in
   * the document itself. This costs about 2.4 KB of the output, which matters
   * because cascade-agent injects the whole document into its system prompt on
   * every session.
   */
  required?: true;
  description: string;
  /** Short form of an option, when one is registered (e.g. `-p`). */
  short?: string;
  /** Present only when a meaningful default is registered. */
  default?: unknown;
  /** Present only when commander restricts the value with `.choices()`. */
  choices?: string[];
}

/** One command of the CLI, addressed by its full invocation path. */
export interface CommandDescriptor {
  /** Full path from the root program, e.g. `pod query`. */
  name: string;
  description: string;
  usage: string;
  parameters: CommandParameter[];
  /** Present when the command is a group: the names of its direct children. */
  subcommands?: string[];
  examples?: string[];
  outputSchema?: Record<string, unknown>;
  notes?: string[];
  status: 'implemented';
}

/**
 * Decoration for one command, keyed by full path in `./enrichment.js`.
 *
 * There is deliberately no `name`, no `usage` and no `parameters` field: an
 * enrichment entry cannot describe a command that is not registered, because it
 * cannot describe a command at all. It can only add to one the registry
 * produced.
 */
export interface CommandEnrichment {
  /** Overrides commander's one-liner when that is too thin to use the verb safely. */
  description?: string;
  examples?: string[];
  outputSchema?: Record<string, unknown>;
  notes?: string[];
}

export type EnrichmentTable = Readonly<Record<string, CommandEnrichment>>;

/** The global options block, hoisted out of the per-command descriptors. */
export interface GlobalOptionsDescriptor {
  position: string;
  options: CommandParameter[];
}

/**
 * Describe every command registered under `program`, depth first.
 *
 * Groups (commands that own subcommands) are emitted too, carrying their child
 * names. Commander does not publicly expose whether an action handler is
 * attached, so "is this invocable" is not a question this walk asks — and a
 * group is worth describing anyway, since it tells the agent that `pod` is a
 * family and what is in it. `agent` is both: it takes a prompt AND owns
 * subcommands.
 */
export function describeCommands(program: Command, enrichment: EnrichmentTable = {}): CommandDescriptor[] {
  const descriptors: CommandDescriptor[] = [];
  walk(program, [], descriptors, enrichment);
  return descriptors;
}

function walk(cmd: Command, prefix: string[], out: CommandDescriptor[], enrichment: EnrichmentTable): void {
  for (const sub of cmd.commands) {
    const parts = [...prefix, sub.name()];
    out.push(describeOne(sub, parts, enrichment));
    walk(sub, parts, out, enrichment);
  }
}

function describeOne(cmd: Command, parts: string[], enrichment: EnrichmentTable): CommandDescriptor {
  const name = parts.join(' ');
  const extra = enrichment[name] ?? {};
  const subcommands = cmd.commands.map((c) => c.name());

  return {
    name,
    description: extra.description ?? cmd.description(),
    usage: buildUsage(name, cmd),
    parameters: [
      ...cmd.registeredArguments.map(describeArgument),
      ...cmd.options.map(describeOption),
    ],
    ...(subcommands.length > 0 ? { subcommands } : {}),
    ...(extra.examples ? { examples: extra.examples } : {}),
    ...(extra.outputSchema ? { outputSchema: extra.outputSchema } : {}),
    ...(extra.notes ? { notes: extra.notes } : {}),
    status: 'implemented',
  };
}

/** `cascade pod import <pod-dir> <files...> [options]` */
function buildUsage(name: string, cmd: Command): string {
  const parts = ['cascade', name];
  for (const arg of cmd.registeredArguments) {
    const label = arg.variadic ? `${arg.name()}...` : arg.name();
    parts.push(arg.required ? `<${label}>` : `[${label}]`);
  }
  // A group with no arguments of its own is invoked through a subcommand; a
  // group that also takes arguments (`agent`) lists them in `subcommands`.
  if (cmd.commands.length > 0 && cmd.registeredArguments.length === 0) {
    parts.push('<subcommand>');
  }
  if (cmd.options.length > 0) parts.push('[options]');
  return parts.join(' ');
}

/** States the omissions the descriptors make, so a reader cannot misread them. */
export const PARAMETER_CONVENTIONS =
  'In tools[].parameters: an entry carries "required": true only when the CLI enforces it, and the key is ' +
  'absent when the parameter is optional. "type": "boolean" is a flag that takes no value; "string[]" is a ' +
  'variadic argument. "default" appears only when a default is registered. mcpTools[].parameters state ' +
  '"required" explicitly on every entry.';

function describeArgument(arg: Argument): CommandParameter {
  return {
    name: arg.name(),
    type: arg.variadic ? 'string[]' : 'string',
    ...(arg.required ? { required: true as const } : {}),
    description: arg.description,
    ...(hasMeaningfulDefault(arg.defaultValue) ? { default: arg.defaultValue as unknown } : {}),
    ...(arg.argChoices ? { choices: arg.argChoices } : {}),
  };
}

export function describeOption(option: Option): CommandParameter {
  const takesValue = option.required || option.optional;
  return {
    name: option.long ?? option.flags,
    type: takesValue ? 'string' : 'boolean',
    // `mandatory` is commander's "must be present after parsing"; `required`
    // on an Option means "takes a value", which is a different question.
    ...(option.mandatory ? { required: true as const } : {}),
    description: option.description,
    ...(option.short ? { short: option.short } : {}),
    ...(hasMeaningfulDefault(option.defaultValue) ? { default: option.defaultValue as unknown } : {}),
    ...(option.argChoices ? { choices: option.argChoices } : {}),
  };
}

/**
 * Emit a default only when it tells the reader something. `false` and `[]` are
 * commander's "not supplied" placeholders for flags and repeatable options.
 */
function hasMeaningfulDefault(value: unknown): boolean {
  if (value === undefined || value === false) return false;
  if (Array.isArray(value) && value.length === 0) return false;
  return true;
}

/**
 * The root program's own options, described once instead of being repeated on
 * every command.
 *
 * The previous hand-written document listed `--json` as a parameter of each
 * command with a usage string implying it belonged at the end, and told readers
 * of `pod doctor` that it had to be placed before `pod`. Both claims were
 * wrong: these are root options, and because the root program does not use
 * commander's positional-options mode it consumes them from anywhere in argv.
 * Verified at v0.13.0 in all three positions.
 */
export function describeGlobalOptions(program: Command): GlobalOptionsDescriptor {
  return {
    position:
      'Declared on the root command, not on any subcommand, and accepted in any position: ' +
      '`cascade --json pod query <pod-dir> --all` and `cascade pod query <pod-dir> --all --json` ' +
      'are equivalent. They are listed here once and are NOT repeated in each command below.',
    options: program.options.map(describeOption),
  };
}
