/**
 * cascade capabilities
 *
 * The machine-readable description of everything this CLI can do. cascade-agent
 * shells out to this command at startup and splices the raw output into its
 * system prompt verbatim, so this document IS what an agent believes the CLI to
 * be: what it omits does not exist, and what it invents will be called.
 *
 * Nothing here is a list of commands. The command descriptors are generated by
 * walking the same commander program `cascade` parses with (see
 * `lib/capabilities/descriptors.ts`), and the MCP tool descriptors are
 * generated by replaying `registerTools` (see `lib/mcp/describe.ts`).
 * Hand-authored prose lives in `lib/capabilities/enrichment.ts` and can only
 * decorate what those two produce.
 */

import { Command } from 'commander';
import { printResult, type OutputOptions } from '../lib/output.js';
import { CLI_VERSION, CLI_PACKAGE_NAME } from '../lib/version.js';
import {
  describeCommands,
  describeGlobalOptions,
  PARAMETER_CONVENTIONS,
  type CommandDescriptor,
  type GlobalOptionsDescriptor,
} from '../lib/capabilities/descriptors.js';
import { COMMAND_ENRICHMENT, MCP_TOOL_ENRICHMENT } from '../lib/capabilities/enrichment.js';
import { describeMcpTools, type McpToolDescriptor } from '../lib/mcp/describe.js';
import { registerTools } from '../lib/mcp/tools.js';

/** Full capabilities output */
export interface CapabilitiesOutput {
  name: string;
  version: string;
  description: string;
  protocol: string;
  parameterConventions: string;
  globalOptions: GlobalOptionsDescriptor;
  securityModel: Record<string, string>;
  tools: CommandDescriptor[];
  mcpTools: McpToolDescriptor[];
}

/**
 * Assemble the document for a given program.
 *
 * Exported so the gates can compare it against an independent walk of the
 * registry rather than against itself.
 */
export function buildCapabilities(program: Command): CapabilitiesOutput {
  return {
    name: CLI_PACKAGE_NAME,
    version: CLI_VERSION,
    description: 'Cascade Protocol CLI - Validate, convert, and manage health data with zero network calls',
    protocol: 'https://cascadeprotocol.org',
    parameterConventions: PARAMETER_CONVENTIONS,
    globalOptions: describeGlobalOptions(program),
    securityModel: {
      networkCalls: 'zero — all operations are local',
      dataStorage: 'local filesystem only',
      provenance: 'all agent-written data tagged with AIGenerated provenance',
      auditLog: 'all MCP operations logged to provenance/audit-log.ttl',
    },
    tools: describeCommands(program, COMMAND_ENRICHMENT),
    mcpTools: describeMcpTools(registerTools, MCP_TOOL_ENRICHMENT),
  };
}

export function registerCapabilitiesCommand(program: Command): void {
  program
    .command('capabilities')
    .description('Show machine-readable tool descriptions')
    .action(() => {
      const globalOpts = program.opts() as OutputOptions;

      // The tree is walked inside the action, after every command has been
      // registered — including `agent`, which is supplied by another package.
      const capabilities = buildCapabilities(program);

      // Capabilities always outputs JSON, regardless of --json flag.
      // This is intentional: the purpose of this command is machine-readable output.
      printResult(capabilities, { json: true, verbose: globalOpts.verbose });
    });
}
