/**
 * The stored daily wellness series: a compact DERIVED VIEW over a pod's
 * wellness records, so a reader can show a daily series and a per-source
 * summary without reading, decrypting and parsing tens of thousands of records.
 *
 * WHAT IT IS. For each reading type and statistic, one value per local day,
 * chosen by the source-priority read rule in
 * `src/data/wellness-daily-series-rules.json` (watch, then phone, then
 * third-party). Each day carries the chosen value, the source and device it
 * came from, the zone its day was cut in and the IRI of the daily record it was
 * taken from, so a reader cites the pod's own record and never this view. Plus
 * one summary row per source: its devices and, per reading type, the days it
 * covers and the first and last of them.
 *
 * WHY IT IS STORED. D-WELLNESS-1's amendment: a computed aggregate is a derived
 * view, stored when it pays, stamped with the version of its rule, and
 * rebuildable. This one pays: the records it summarises cost seconds and
 * gigabytes to read on every bind, and the view costs a few megabytes.
 *
 * WHAT IT IS NOT. Not a record and not layer 1: it names nothing, nothing
 * durable points at it, and deleting it loses nothing. The import writes one
 * record per (source, device, metric, statistic, day) and never picks a winner;
 * this view is where the reader's rule is applied, once, in one place.
 *
 * DETERMINISM. The view is a function of the records' triples, the pod's day
 * zone and the rule table, and nothing else: no clock, no file order, no run
 * value. Everything is sorted before it is written, so rebuilding it, or
 * deleting it and importing again, gives the same bytes.
 *
 * WHERE (provisional). The JSON bytes are a content-addressed attachment,
 * `attachments/sha-256/<digest>` (pod-structure.md section 4.3), sealed like
 * every other pod file on an encrypted pod. The descriptor,
 * `wellness/series/daily-series.ttl`, is a `cascade:Attachment` generated by an
 * activity stamped `cascade:version "wellness-daily-series/<ruleVersion>"`. The
 * series itself stays in the JSON: the bundled vocabulary has no terms for a
 * chosen-day row, and this CLI does not invent them.
 */

import { createHash } from 'node:crypto';
import path from 'node:path';
import { DataFactory, type Quad } from 'n3';
import seriesRulesAsset from '../../data/wellness-daily-series-rules.json' with { type: 'json' };
import { WELLNESS_DAILY_SERIES_DESCRIPTOR, excludableDataFiles } from '../pod-data-types.js';
import { PodReader, type PodReadFailure, type PodReadResult } from '../pod-read.js';
import { writeResource, writeResourceBytes, readResourceBytes } from '../pod-encryption.js';
import { mkdirInPod, podPathExists, removePodFile } from '../pod-path.js';
import { serializeBucket } from '../bucket-write.js';
import { ensurePodIdentifier, readUsablePodIdentifier } from '../pod-identifier.js';
import { wellnessSupportSeed } from '../identity.js';
import { deterministicUuid } from '../fhir-converter/types.js';
import { isKnownZone, localDateOf } from './time.js';

const { namedNode, literal, quad } = DataFactory;

const RDF_TYPE = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type';
const XSD = 'http://www.w3.org/2001/XMLSchema#';
const CASCADE = 'https://ns.cascadeprotocol.org/core/v1#';
const HEALTH = 'https://ns.cascadeprotocol.org/health/v1#';
const PROV = 'http://www.w3.org/ns/prov#';
const DCT = 'http://purl.org/dc/terms/';

const PREFIXES: Record<string, string> = { cascade: CASCADE, health: HEALTH };

/** The descriptor's prefixes: only the namespaces it writes. */
const DESCRIPTOR_PREFIXES: Record<string, string> = { cascade: CASCADE, prov: PROV, xsd: XSD };

/** The JSON's `format`, and the version of its layout (not of the rule). */
export const DAILY_SERIES_FORMAT = 'cascade-wellness-daily-series';
export const DAILY_SERIES_FORMAT_VERSION = 1;

const LOCAL_ORIGIN = 'https://pod.invalid';

// ---------------------------------------------------------------------------
// The rule table
// ---------------------------------------------------------------------------

/** One kind of wellness record the view reads, as the rule table states it. */
export interface ReadingTypeRule {
  /** Full IRI of the record class. */
  classIri: string;
  /** A fixed key, or (`keyFrom`) the predicate whose value's local name is the key. */
  key?: string;
  keyFrom?: string;
  /** Predicate carrying the number (series types only). */
  value?: string;
  /** A fixed unit, or the predicate carrying it. */
  unit?: string;
  unitFrom?: string;
  /** Predicate carrying the instant whose local date is the record's day. */
  day: string;
  /** True when the type has a daily series; false when it is only summarised. */
  series: boolean;
}

export interface TierRule {
  label: string;
  manufacturer: RegExp;
  hardware: RegExp;
  nameWhenUnstated: RegExp;
}

export interface DailySeriesRules {
  rule: string;
  ruleVersion: string;
  /** Pod data-type keys whose files the view is built from, in the table's order. */
  inputs: string[];
  tiers: TierRule[];
  otherTier: string;
  readingTypes: ReadingTypeRule[];
}

function expand(curie: string): string {
  const i = curie.indexOf(':');
  const ns = i > 0 ? PREFIXES[curie.slice(0, i)] : undefined;
  if (!ns) throw new Error(`wellness daily series rules: unknown prefix in "${curie}"`);
  return ns + curie.slice(i + 1);
}

let cachedRules: DailySeriesRules | undefined;

/** The rule table, read and checked once. Throws on a table this module cannot apply. */
export function dailySeriesRules(): DailySeriesRules {
  if (cachedRules) return cachedRules;
  const raw = seriesRulesAsset as unknown as {
    rule: string;
    ruleVersion: string;
    inputs: string[];
    tiers: Array<{ label: string; manufacturer: string; hardware: string; nameWhenUnstated: string }>;
    otherTier: string;
    patternFlags: string;
    readingTypes: Array<{
      class: string;
      key?: string;
      keyFrom?: string;
      value?: string;
      unit?: string;
      unitFrom?: string;
      day: string;
      series: boolean;
    }>;
  };
  const known = new Set(excludableDataFiles().map((e) => e.key));
  for (const key of raw.inputs) {
    if (!known.has(key)) throw new Error(`wellness daily series rules: unknown input data type "${key}"`);
  }
  const readingTypes = raw.readingTypes.map((t): ReadingTypeRule => {
    if ((t.key === undefined) === (t.keyFrom === undefined)) {
      throw new Error(`wellness daily series rules: ${t.class} needs exactly one of key and keyFrom`);
    }
    if (t.series && (t.value === undefined || (t.unit === undefined) === (t.unitFrom === undefined))) {
      throw new Error(`wellness daily series rules: series type ${t.class} needs a value and exactly one of unit and unitFrom`);
    }
    return {
      classIri: expand(t.class),
      key: t.key,
      keyFrom: t.keyFrom === undefined ? undefined : expand(t.keyFrom),
      value: t.value === undefined ? undefined : expand(t.value),
      unit: t.unit,
      unitFrom: t.unitFrom === undefined ? undefined : expand(t.unitFrom),
      day: expand(t.day),
      series: t.series,
    };
  });
  cachedRules = {
    rule: raw.rule,
    ruleVersion: raw.ruleVersion,
    inputs: raw.inputs,
    tiers: raw.tiers.map((t) => ({
      label: t.label,
      manufacturer: new RegExp(t.manufacturer, raw.patternFlags),
      hardware: new RegExp(t.hardware, raw.patternFlags),
      nameWhenUnstated: new RegExp(t.nameWhenUnstated, raw.patternFlags),
    })),
    otherTier: raw.otherTier,
    readingTypes,
  };
  return cachedRules;
}

/** The files the view is built from, by data-type key and pod-relative path, in the table's order. */
export function dailySeriesInputs(): Array<{ key: string; file: string }> {
  const files = new Map(excludableDataFiles().map((e) => [e.key, e.file]));
  return dailySeriesRules().inputs.map((key) => ({ key, file: files.get(key)! }));
}

/** Pod-relative paths of the files the view is built from, in the table's order. */
export function dailySeriesInputFiles(): string[] {
  return dailySeriesInputs().map((i) => i.file);
}

// ---------------------------------------------------------------------------
// The view
// ---------------------------------------------------------------------------

/** One source's contribution of one reading type. */
export interface SourceReadingTypeSummary {
  key: string;
  /** Distinct local days with at least one record of this type from this source. */
  days: number;
  first: string;
  last: string;
}

export interface DailySeriesSource {
  name: string;
  /** Index into `tiers`. */
  tier: number;
  /** Records of the view's reading types this source wrote. */
  records: number;
  /** Indexes into `devices`, ascending. */
  devices: number[];
  readingTypes: SourceReadingTypeSummary[];
}

export interface DailySeriesDevice {
  iri: string;
  name?: string;
  model?: string;
  hardware?: string;
  manufacturers: string[];
  /** Index into `tiers`. */
  tier: number;
}

/** One reading type and statistic, one row per local day, as parallel columns. */
export interface DailySeriesColumns {
  key: string;
  /** `cascade:statistic`, or "" when the records state none. */
  statistic: string;
  /** The unit every row is in, or null when the rows differ (then see `units`). */
  unit: string | null;
  units?: string[];
  date: string[];
  value: number[];
  source: number[];
  device: Array<number | null>;
  tier: number[];
  zone: number[];
  record: string[];
  alternatives: number[];
}

export interface DailySeriesView {
  format: typeof DAILY_SERIES_FORMAT;
  formatVersion: number;
  rule: string;
  ruleVersion: string;
  /** The pod's `cascade:dayZone` when the view was built, or null. */
  dayZone: string | null;
  /** SHA-256 of each input file's plaintext: what the view was built from. */
  inputs: Array<{ path: string; sha256: string }>;
  /**
   * Records each input file holds, by data-type key (typed subjects that are
   * not provenance nodes): the count `pod query` would report for its bucket.
   */
  recordCounts: Record<string, number>;
  columns: Record<string, string>;
  tiers: string[];
  zones: string[];
  devices: DailySeriesDevice[];
  sources: DailySeriesSource[];
  series: DailySeriesColumns[];
}

const COLUMN_DOC: Record<string, string> = {
  date: 'the local day, YYYY-MM-DD, in the zone the record was cut in',
  value: 'the chosen record\'s value, as a number',
  source: 'index into sources: the source the chosen record came from',
  device: 'index into devices: the device the chosen record names, or null',
  tier: 'index into tiers: the tier that won the day',
  zone: 'index into zones: the zone the day was cut in',
  record: 'IRI of the daily record the value was taken from; cite this, never the view',
  alternatives: 'how many other sources (source and device) reported the same type and statistic that day; a source\'s older versions of the day are not counted',
  units: 'present only when the rows of one series differ in unit',
};

const cmpStr = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

/** The local name of an IRI: `http://loinc.org/rdf#8867-4` -> `8867-4`. */
function localName(iri: string): string {
  const i = Math.max(iri.lastIndexOf('#'), iri.lastIndexOf('/'));
  return i >= 0 ? iri.slice(i + 1) : iri;
}

/** The predicates a subject is reduced to: nothing else is kept in memory. */
function neededPredicates(rules: DailySeriesRules): Set<string> {
  const s = new Set<string>([
    RDF_TYPE,
    CASCADE + 'sourceDeviceName',
    CASCADE + 'sampleCount',
    CASCADE + 'statistic',
    HEALTH + 'device',
    HEALTH + 'timeZone',
    HEALTH + 'deviceName',
    HEALTH + 'deviceModel',
    HEALTH + 'hardwareVersion',
    HEALTH + 'deviceManufacturer',
    // How a record is dated by import: record -> sample group -> pack -> export.
    PROV + 'wasDerivedFrom',
    PROV + 'generatedAtTime',
    DCT + 'hasPart',
  ]);
  for (const t of rules.readingTypes) {
    for (const p of [t.keyFrom, t.value, t.unitFrom, t.day]) if (p) s.add(p);
  }
  return s;
}

/**
 * Builds the view from the input files' triples, one file at a time, keeping
 * only the predicates the rule reads, so the triples of every file never sit
 * in memory together.
 */
export class DailySeriesBuilder {
  private readonly rules: DailySeriesRules;
  private readonly needed: Set<string>;
  private readonly subjects = new Map<string, Map<string, string[]>>();
  private readonly recordsByFile = new Map<string, Set<string>>();

  constructor(rules: DailySeriesRules = dailySeriesRules()) {
    this.rules = rules;
    this.needed = neededPredicates(rules);
  }

  /**
   * Add the triples of one input file. Blank-node subjects are skipped: nothing
   * can cite them. `dataTypeKey` names the file, so the view can say how many
   * records each file holds without a reader opening it.
   */
  addQuads(quads: Iterable<Quad>, dataTypeKey?: string): void {
    const sink = this.sink(dataTypeKey);
    for (const q of quads) sink(q);
  }

  /** {@link addQuads} one triple at a time, for a streamed parse. */
  sink(dataTypeKey?: string): (q: Quad) => void {
    let counted: Set<string> | undefined;
    if (dataTypeKey !== undefined) {
      counted = this.recordsByFile.get(dataTypeKey);
      if (!counted) this.recordsByFile.set(dataTypeKey, (counted = new Set()));
    }
    return (q: Quad): void => {
      if (q.subject.termType !== 'NamedNode') return;
      if (counted && q.predicate.value === RDF_TYPE && !q.object.value.startsWith(PROV)) counted.add(q.subject.value);
      if (!this.needed.has(q.predicate.value)) return;
      let props = this.subjects.get(q.subject.value);
      if (!props) this.subjects.set(q.subject.value, (props = new Map()));
      const values = props.get(q.predicate.value);
      if (values) values.push(q.object.value);
      else props.set(q.predicate.value, [q.object.value]);
    };
  }

  /**
   * The view, as a value. `dayZone` cuts the day of a record that states no
   * zone of its own; `inputs` is recorded as given.
   */
  finish(opts: { dayZone?: string; inputs: Array<{ path: string; sha256: string }> }): DailySeriesView {
    const rules = this.rules;
    const other = rules.tiers.length;
    const first = (props: Map<string, string[]>, p: string): string | undefined => {
      const v = props.get(p);
      if (!v || v.length === 0) return undefined;
      return v.length === 1 ? v[0] : [...v].sort(cmpStr)[0];
    };
    const podZone = opts.dayZone && isKnownZone(opts.dayZone) ? opts.dayZone : 'UTC';

    // Devices: tiered by manufacturer + hardware, names only when neither is stated.
    const deviceTier = (d: { name?: string; model?: string; hardware?: string; manufacturers: string[] }): number => {
      const hardware = d.hardware?.trim() ?? '';
      const makers = d.manufacturers.map((m) => m.trim()).filter(Boolean);
      if (hardware && makers.length > 0) {
        for (let i = 0; i < rules.tiers.length; i++) {
          const t = rules.tiers[i];
          if (makers.some((m) => t.manufacturer.test(m)) && t.hardware.test(hardware)) return i;
        }
        return other;
      }
      const name = [d.name, d.model].filter(Boolean).join(' ');
      for (let i = 0; i < rules.tiers.length; i++) if (rules.tiers[i].nameWhenUnstated.test(name)) return i;
      return other;
    };
    const devicesByIri = new Map<string, DailySeriesDevice>();
    for (const [iri, props] of this.subjects) {
      if (!(props.get(RDF_TYPE) ?? []).includes(HEALTH + 'Device')) continue;
      const d: DailySeriesDevice = {
        iri,
        name: first(props, HEALTH + 'deviceName'),
        model: first(props, HEALTH + 'deviceModel'),
        hardware: first(props, HEALTH + 'hardwareVersion'),
        manufacturers: [...new Set(props.get(HEALTH + 'deviceManufacturer') ?? [])].sort(cmpStr),
        tier: other,
      };
      d.tier = deviceTier(d);
      devicesByIri.set(iri, d);
    }

    // Entries: one per (record, reading type it carries).
    interface Entry {
      iri: string;
      key: string;
      statistic: string;
      series: boolean;
      value?: number;
      unit?: string;
      date: string;
      zone: string;
      source: string;
      device?: string;
      sampleCount: number;
      /** Epoch ms of the newest export reaching the record's sample group; -Infinity when none does. */
      imported: number;
    }

    // Import dates: export -> packs -> groups, the newest export per group.
    const groupImported = new Map<string, number>();
    for (const props of this.subjects.values()) {
      const when = first(props, PROV + 'generatedAtTime');
      const packs = props.get(DCT + 'hasPart');
      if (when === undefined || !packs) continue;
      const ms = Date.parse(when);
      if (!Number.isFinite(ms)) continue;
      for (const pack of packs) {
        for (const group of this.subjects.get(pack)?.get(DCT + 'hasPart') ?? []) {
          if (ms > (groupImported.get(group) ?? -Infinity)) groupImported.set(group, ms);
        }
      }
    }
    const importedOf = (props: Map<string, string[]>): number => {
      let best = -Infinity;
      for (const g of props.get(PROV + 'wasDerivedFrom') ?? []) best = Math.max(best, groupImported.get(g) ?? -Infinity);
      return best;
    };

    const entries: Entry[] = [];
    const recordSource = new Map<string, { source: string; device?: string }>();
    for (const [iri, props] of this.subjects) {
      const types = props.get(RDF_TYPE) ?? [];
      for (const t of rules.readingTypes) {
        if (!types.includes(t.classIri)) continue;
        const raw = t.value === undefined ? undefined : first(props, t.value);
        // A series type is carried only by a record that states its value
        // predicate: an activity snapshot holds one of several metrics.
        if (t.series && raw === undefined) continue;
        const key = t.key ?? (t.keyFrom ? first(props, t.keyFrom) : undefined);
        if (key === undefined) continue;
        const dayInstant = first(props, t.day);
        const ms = dayInstant === undefined ? NaN : Date.parse(dayInstant);
        if (!Number.isFinite(ms)) continue;
        const stated = first(props, HEALTH + 'timeZone');
        const zone = stated && isKnownZone(stated) ? stated : podZone;
        const deviceIri = first(props, HEALTH + 'device');
        const source = first(props, CASCADE + 'sourceDeviceName') ?? '';
        const n = raw === undefined ? NaN : Number(raw);
        const sc = Number(first(props, CASCADE + 'sampleCount'));
        entries.push({
          iri,
          key: t.key ?? localName(key),
          statistic: first(props, CASCADE + 'statistic') ?? '',
          series: t.series,
          value: Number.isFinite(n) ? n : undefined,
          unit: t.unit ?? (t.unitFrom ? first(props, t.unitFrom) : undefined),
          date: localDateOf(ms, zone),
          zone,
          source,
          device: deviceIri !== undefined && devicesByIri.has(deviceIri) ? deviceIri : undefined,
          sampleCount: Number.isFinite(sc) ? sc : 0,
          imported: importedOf(props),
        });
        recordSource.set(iri, { source, device: deviceIri !== undefined && devicesByIri.has(deviceIri) ? deviceIri : undefined });
      }
    }
    this.subjects.clear();

    // Source tiers: the tier its device-bearing records predominantly name
    // (each record counted once); a tie goes to the better tier; none, other.
    const tally = new Map<string, number[]>();
    for (const { source, device } of recordSource.values()) {
      if (!tally.has(source)) tally.set(source, new Array<number>(other + 1).fill(0));
      if (device) tally.get(source)![devicesByIri.get(device)!.tier]++;
    }
    const sourceTier = new Map<string, number>();
    for (const [source, t] of tally) {
      let best = other;
      let bestCount = 0;
      for (let i = 0; i <= other; i++) {
        if (t[i] > bestCount) {
          best = i;
          bestCount = t[i];
        }
      }
      sourceTier.set(source, best);
    }
    const tierOf = (e: Entry): number => (e.device ? devicesByIri.get(e.device)!.tier : sourceTier.get(e.source) ?? other);

    // Tables. Devices by IRI; sources by tier, then records, then name.
    const devices = [...devicesByIri.values()].sort((a, b) => cmpStr(a.iri, b.iri));
    const deviceIndex = new Map(devices.map((d, i) => [d.iri, i]));
    interface SourceAcc {
      records: Set<string>;
      devices: Set<number>;
      types: Map<string, Set<string>>;
    }
    const sourceAcc = new Map<string, SourceAcc>();
    for (const e of entries) {
      let a = sourceAcc.get(e.source);
      if (!a) sourceAcc.set(e.source, (a = { records: new Set(), devices: new Set(), types: new Map() }));
      a.records.add(e.iri);
      if (e.device) a.devices.add(deviceIndex.get(e.device)!);
      let days = a.types.get(e.key);
      if (!days) a.types.set(e.key, (days = new Set()));
      days.add(e.date);
    }
    const sources: DailySeriesSource[] = [...sourceAcc.entries()]
      .map(([name, a]) => ({
        name,
        tier: sourceTier.get(name) ?? other,
        records: a.records.size,
        devices: [...a.devices].sort((x, y) => x - y),
        readingTypes: [...a.types.entries()]
          .map(([key, days]) => {
            const sorted = [...days].sort(cmpStr);
            return { key, days: sorted.length, first: sorted[0], last: sorted[sorted.length - 1] };
          })
          .sort((x, y) => cmpStr(x.key, y.key)),
      }))
      .sort((a, b) => a.tier - b.tier || b.records - a.records || cmpStr(a.name, b.name));
    const sourceIndex = new Map(sources.map((s, i) => [s.name, i]));

    // Series: one row per (key, statistic, day), the best candidate by the tie-break.
    const groups = new Map<string, Entry[]>();
    for (const e of entries) {
      if (!e.series || e.value === undefined) continue;
      const k = `${e.key}\u0000${e.statistic}\u0000${e.date}`;
      const g = groups.get(k);
      if (g) g.push(e);
      else groups.set(k, [e]);
    }
    // Within one source and device, the most recent import wins (D-WELLNESS-1,
    // amendment of 2026-09-25, item 4); across sources, the tier rule.
    const newer = (a: Entry, b: Entry): number =>
      (a.imported === b.imported ? 0 : a.imported > b.imported ? -1 : 1) || b.sampleCount - a.sampleCount || cmpStr(a.iri, b.iri);
    const better = (a: Entry, b: Entry): number =>
      tierOf(a) - tierOf(b) || b.sampleCount - a.sampleCount || cmpStr(a.source, b.source) || cmpStr(a.iri, b.iri);
    const chosenBySeries = new Map<string, Array<{ e: Entry; alternatives: number }>>();
    for (const all of groups.values()) {
      const bySource = new Map<string, Entry>();
      for (const e of all) {
        const k = `${e.source}\u0000${e.device ?? ''}`;
        const held = bySource.get(k);
        if (!held || newer(e, held) < 0) bySource.set(k, e);
      }
      const g = [...bySource.values()].sort(better);
      const e = g[0];
      const sk = `${e.key}\u0000${e.statistic}`;
      let rows = chosenBySeries.get(sk);
      if (!rows) chosenBySeries.set(sk, (rows = []));
      rows.push({ e, alternatives: g.length - 1 });
    }
    const zoneSet = new Set<string>();
    for (const rows of chosenBySeries.values()) for (const r of rows) zoneSet.add(r.e.zone);
    const zones = [...zoneSet].sort(cmpStr);
    const zoneIndex = new Map(zones.map((z, i) => [z, i]));
    const series: DailySeriesColumns[] = [...chosenBySeries.entries()]
      .sort((a, b) => cmpStr(a[0], b[0]))
      .map(([, rows]) => {
        rows.sort((a, b) => cmpStr(a.e.date, b.e.date));
        const units = rows.map((r) => r.e.unit ?? '');
        const oneUnit = units.every((u) => u === units[0]);
        const col: DailySeriesColumns = {
          key: rows[0].e.key,
          statistic: rows[0].e.statistic,
          unit: oneUnit ? units[0] : null,
          date: rows.map((r) => r.e.date),
          value: rows.map((r) => r.e.value!),
          source: rows.map((r) => sourceIndex.get(r.e.source)!),
          device: rows.map((r) => (r.e.device ? deviceIndex.get(r.e.device)! : null)),
          tier: rows.map((r) => tierOf(r.e)),
          zone: rows.map((r) => zoneIndex.get(r.e.zone)!),
          record: rows.map((r) => r.e.iri),
          alternatives: rows.map((r) => r.alternatives),
        };
        if (!oneUnit) col.units = units;
        return col;
      });

    return {
      format: DAILY_SERIES_FORMAT,
      formatVersion: DAILY_SERIES_FORMAT_VERSION,
      rule: rules.rule,
      ruleVersion: rules.ruleVersion,
      dayZone: opts.dayZone ?? null,
      inputs: [...opts.inputs].sort((a, b) => cmpStr(a.path, b.path)),
      recordCounts: Object.fromEntries(
        [...this.recordsByFile.entries()].sort((a, b) => cmpStr(a[0], b[0])).map(([k, v]) => [k, v.size]),
      ),
      columns: COLUMN_DOC,
      tiers: [...rules.tiers.map((t) => t.label), rules.otherTier],
      zones,
      devices,
      sources,
      series,
    };
  }
}

/** The view's bytes: compact JSON, one trailing newline. */
export function dailySeriesBytes(view: DailySeriesView): Buffer {
  return Buffer.from(JSON.stringify(view) + '\n', 'utf8');
}

// ---------------------------------------------------------------------------
// Reading the stored view
// ---------------------------------------------------------------------------

export interface StoredDailySeries {
  /** Pod-relative path of the descriptor. */
  descriptor: string;
  /** Pod-relative path of the JSON attachment. */
  attachment: string;
  contentHash: string;
  byteSize: number;
  /** `cascade:version` of the activity the descriptor names. */
  generatedBy: string;
  view: DailySeriesView;
}

function readFailure(rel: string, kind: PodReadFailure['kind'], reason: string): { ok: false; failure: PodReadFailure } {
  return { ok: false, failure: { file: rel, kind, reason } };
}

/**
 * Read the stored view: the descriptor, then the attachment it names, whose
 * bytes are checked against the digest the descriptor states. `null` when the
 * pod holds no view.
 */
export function readStoredDailySeries(reader: PodReader): PodReadResult<StoredDailySeries | null> {
  const rel = WELLNESS_DAILY_SERIES_DESCRIPTOR;
  const abs = path.join(reader.podDir, ...rel.split('/'));
  if (!podPathExists(reader.podDir, rel)) return { ok: true, value: null };
  const parsed = reader.parseFile(abs, { baseIri: `${LOCAL_ORIGIN}/${rel}` });
  if (!parsed.ok) return parsed;
  const quads = parsed.value.quads;
  const att = quads.find((q) => q.predicate.value === RDF_TYPE && q.object.value === CASCADE + 'Attachment')?.subject.value;
  const of = (s: string | undefined, p: string): string | undefined =>
    s === undefined ? undefined : quads.find((q) => q.subject.value === s && q.predicate.value === p)?.object.value;
  const attachment = of(att, CASCADE + 'attachmentPath');
  const contentHash = of(att, CASCADE + 'contentHash');
  const activity = of(att, PROV + 'wasGeneratedBy');
  const generatedBy = of(activity, CASCADE + 'version');
  if (!attachment || !contentHash || !generatedBy || !/^attachments\/sha-256\/[0-9a-f]{64}$/.test(attachment)) {
    return readFailure(rel, 'parse', 'the daily series descriptor does not name an attachment, its digest and its rule version');
  }
  const text = reader.readText(path.join(reader.podDir, ...attachment.split('/')));
  if (!text.ok) return text;
  const bytes = Buffer.from(text.value, 'utf8');
  if (createHash('sha256').update(bytes).digest('hex') !== contentHash) {
    return readFailure(attachment, 'parse', 'the daily series attachment does not hold the bytes its descriptor names');
  }
  let view: DailySeriesView;
  try {
    view = JSON.parse(text.value) as DailySeriesView;
  } catch (e: unknown) {
    return readFailure(attachment, 'parse', e instanceof Error ? e.message : String(e));
  }
  if (view.format !== DAILY_SERIES_FORMAT || typeof view.formatVersion !== 'number') {
    return readFailure(attachment, 'parse', `not a ${DAILY_SERIES_FORMAT} document`);
  }
  return { ok: true, value: { descriptor: rel, attachment, contentHash, byteSize: bytes.length, generatedBy, view } };
}

// ---------------------------------------------------------------------------
// Keeping the stored view current
// ---------------------------------------------------------------------------

export interface DailySeriesRefresh {
  /**
   * `built`   the view was written (it was missing, stale, or forced);
   * `current` the stored view was built from exactly these inputs by this rule;
   * `removed` the pod holds no inputs any more, so the view was deleted;
   * `absent`  no inputs and no view: nothing to do.
   */
  status: 'built' | 'current' | 'removed' | 'absent';
  ruleVersion: string;
  descriptor?: string;
  attachment?: string;
  byteSize?: number;
  series?: number;
  days?: number;
  sources?: number;
}

/** The pod's `cascade:dayZone` as the profile states it, if it states one. */
function podDayZone(reader: PodReader): string | undefined {
  const rel = 'profile/extended.ttl';
  if (!podPathExists(reader.podDir, rel)) return undefined;
  const r = reader.parseFile(path.join(reader.podDir, rel), { baseIri: `${LOCAL_ORIGIN}/${rel}` });
  if (!r.ok) return undefined;
  return r.value.quads.find((q) => q.predicate.value === CASCADE + 'dayZone' && q.object.termType === 'Literal')?.object.value;
}

function sameInputs(a: DailySeriesView['inputs'], b: DailySeriesView['inputs']): boolean {
  return a.length === b.length && a.every((x, i) => x.path === b[i].path && x.sha256 === b[i].sha256);
}

/**
 * SHA-256 of each input file's plaintext, sorted by path: what a view built
 * now would record. Read, never parsed (about 60 ms for a year of wellness).
 */
export function hashDailySeriesInputs(
  reader: PodReader,
): PodReadResult<{ present: string[]; inputs: DailySeriesView['inputs'] }> {
  const present = dailySeriesInputFiles().filter((rel) => podPathExists(reader.podDir, rel));
  const inputs: DailySeriesView['inputs'] = [];
  for (const rel of present) {
    const text = reader.readText(path.join(reader.podDir, ...rel.split('/')));
    if (!text.ok) return text;
    inputs.push({ path: rel, sha256: createHash('sha256').update(text.value, 'utf8').digest('hex') });
  }
  inputs.sort((a, b) => cmpStr(a.path, b.path));
  return { ok: true, value: { present, inputs } };
}

/** Why a stored view is not what this rule would build from the pod now; empty when it is. */
function staleReasons(held: StoredDailySeries, inputs: DailySeriesView['inputs'], dayZone: string | undefined): string[] {
  const rules = dailySeriesRules();
  const reasons: string[] = [];
  if (
    held.view.formatVersion !== DAILY_SERIES_FORMAT_VERSION ||
    held.view.ruleVersion !== rules.ruleVersion ||
    held.generatedBy !== `${rules.rule}/${rules.ruleVersion}`
  ) {
    reasons.push(`it was built by ${held.generatedBy}, and this release applies ${rules.rule}/${rules.ruleVersion}`);
  }
  if ((held.view.dayZone ?? undefined) !== dayZone) reasons.push("the pod's day zone changed since it was built");
  if (!sameInputs(held.view.inputs, inputs)) {
    const was = new Map(held.view.inputs.map((i) => [i.path, i.sha256]));
    const now = new Map(inputs.map((i) => [i.path, i.sha256]));
    const changed = [...new Set([...was.keys(), ...now.keys()])].filter((k) => was.get(k) !== now.get(k)).sort(cmpStr);
    reasons.push(`the wellness files it was built from changed since (${changed.join(', ')})`);
  }
  return reasons;
}

/**
 * Is a stored view still what the pod's records say? Checked on every read,
 * because a writer that does not rebuild it (an older release, another tool,
 * an import stopped between its writes and the rebuild) leaves it describing
 * records the pod no longer holds. A stale view is still returned, marked, so
 * a reader can choose; it is never presented as current.
 */
export function dailySeriesFreshness(reader: PodReader, held: StoredDailySeries): PodReadResult<{ stale: boolean; reasons: string[] }> {
  const hashed = hashDailySeriesInputs(reader);
  if (!hashed.ok) return hashed;
  const reasons = staleReasons(held, hashed.value.inputs, podDayZone(reader));
  return { ok: true, value: { stale: reasons.length > 0, reasons } };
}

function urn(seed: string): string {
  return `urn:uuid:${deterministicUuid(seed)}`;
}

/** The descriptor's triples: the attachment and the activity that stamps the rule version. */
function descriptorQuads(podSubject: string, digest: string, byteSize: number, rules: DailySeriesRules): Quad[] {
  const att = namedNode(urn(wellnessSupportSeed({ podSubject, kind: 'attachment', key: `sha-256/${digest}` })));
  const act = namedNode(urn(wellnessSupportSeed({ podSubject, kind: 'rule', key: `${rules.rule}/${rules.ruleVersion}` })));
  const version = `${rules.rule}/${rules.ruleVersion}`;
  const out = [
    quad(att, namedNode(RDF_TYPE), namedNode(CASCADE + 'Attachment')),
    quad(att, namedNode(CASCADE + 'attachmentPath'), literal(`attachments/sha-256/${digest}`)),
    quad(att, namedNode(CASCADE + 'contentHash'), literal(digest)),
    quad(att, namedNode(CASCADE + 'hashAlgorithm'), literal('sha-256')),
    quad(att, namedNode(CASCADE + 'attachmentMediaType'), literal('application/json')),
    quad(att, namedNode(CASCADE + 'byteSize'), literal(String(byteSize), namedNode(XSD + 'integer'))),
    quad(att, namedNode(CASCADE + 'attachmentTitle'), literal(`Daily wellness series, a derived view (${version})`)),
    quad(att, namedNode(PROV + 'wasGeneratedBy'), act),
    quad(act, namedNode(RDF_TYPE), namedNode(PROV + 'Activity')),
    quad(
      act,
      namedNode(PROV + 'label'),
      literal(
        `Daily wellness series: one reading per reading type, statistic and local day, chosen by source priority (${rules.rule}, rule version ${rules.ruleVersion})`,
      ),
    ),
    quad(act, namedNode(CASCADE + 'version'), literal(version)),
  ];
  const key = (q: Quad): string => `${q.subject.value}\u0000${q.predicate.value}\u0000${q.object.value}`;
  return out.sort((a, b) => cmpStr(key(a), key(b)));
}

/**
 * Bring the stored view in line with the pod's wellness records.
 *
 * Cheap when nothing changed: each input file is read and hashed (never
 * parsed), and compared with the digests the stored view records, together
 * with the day zone and the rule version. Only a difference, a missing view or
 * `force` rebuilds it. A view whose inputs are all gone is deleted.
 *
 * Every write verb that can change a wellness file calls this after its
 * writes, so the view never outlives the records it was built from.
 */
export async function refreshWellnessDailySeries(reader: PodReader, opts: { force?: boolean } = {}): Promise<DailySeriesRefresh> {
  const rules = dailySeriesRules();
  const podDir = reader.podDir;
  const dek = reader.dek;
  const hashed = hashDailySeriesInputs(reader);
  if (!hashed.ok) throw new Error(`could not read ${hashed.failure.file}: ${hashed.failure.reason}`);
  const { present, inputs } = hashed.value;

  // A stored view that cannot be read is replaced, never trusted: it is a
  // cache, and the records it came from are all still here.
  const stored = readStoredDailySeries(reader);
  const held = stored.ok ? stored.value : null;
  const descriptorPresent = podPathExists(podDir, WELLNESS_DAILY_SERIES_DESCRIPTOR);

  const removeView = (): void => {
    if (held && podPathExists(podDir, held.attachment)) removePodFile(podDir, held.attachment);
    if (descriptorPresent) removePodFile(podDir, WELLNESS_DAILY_SERIES_DESCRIPTOR);
  };

  if (present.length === 0) {
    if (!descriptorPresent) return { status: 'absent', ruleVersion: rules.ruleVersion };
    removeView();
    return { status: 'removed', ruleVersion: rules.ruleVersion };
  }

  const dayZone = podDayZone(reader);
  if (!opts.force && held && staleReasons(held, inputs, dayZone).length === 0) {
    return summary('current', held.view, held.descriptor, held.attachment, held.byteSize);
  }

  // Streamed, one triple at a time, into a builder that keeps only the
  // predicates the rule reads: no file's triples are ever held whole.
  const builder = new DailySeriesBuilder(rules);
  const keyOf = new Map(dailySeriesInputs().map((i) => [i.file, i.key]));
  for (const rel of present) {
    const sink = builder.sink(keyOf.get(rel));
    const streamed = await reader.streamFile(path.join(podDir, ...rel.split('/')), sink, { baseIri: `${LOCAL_ORIGIN}/${rel}` });
    if (!streamed.ok) throw new Error(`could not read ${rel}: ${streamed.failure.reason}`);
  }
  const view = builder.finish({ dayZone, inputs });
  const bytes = dailySeriesBytes(view);
  const digest = createHash('sha256').update(bytes).digest('hex');
  const attachment = `attachments/sha-256/${digest}`;

  // Named from the pod subject like every other wellness node. A pod holding
  // wellness records has one (the import mints it before naming anything); a
  // pod whose records arrived some other way gets one here, before any name.
  const podSubject = readUsablePodIdentifier(podDir, dek) ?? ensurePodIdentifier(podDir, dek).value;

  // Bytes first, then the descriptor that names them, then the old bytes.
  let intact = false;
  if (podPathExists(podDir, attachment)) {
    try {
      intact = readResourceBytes(podDir, attachment, dek).equals(bytes);
    } catch {
      intact = false;
    }
  }
  if (!intact) {
    mkdirInPod(podDir, 'attachments/sha-256');
    writeResourceBytes(podDir, attachment, bytes, dek);
  }
  mkdirInPod(podDir, path.posix.dirname(WELLNESS_DAILY_SERIES_DESCRIPTOR));
  const ttl = await serializeBucket(descriptorQuads(podSubject, digest, bytes.length, rules), DESCRIPTOR_PREFIXES);
  writeResource(podDir, WELLNESS_DAILY_SERIES_DESCRIPTOR, ttl, dek);
  if (held && held.attachment !== attachment && podPathExists(podDir, held.attachment)) {
    removePodFile(podDir, held.attachment);
  }
  return summary('built', view, WELLNESS_DAILY_SERIES_DESCRIPTOR, attachment, bytes.length);
}

function summary(
  status: DailySeriesRefresh['status'],
  view: DailySeriesView,
  descriptor: string,
  attachment: string,
  byteSize: number,
): DailySeriesRefresh {
  return {
    status,
    ruleVersion: view.ruleVersion,
    descriptor,
    attachment,
    byteSize,
    series: view.series.length,
    days: view.series.reduce((a, s) => a + s.date.length, 0),
    sources: view.sources.length,
  };
}

/**
 * {@link refreshWellnessDailySeries} for a write verb, after its writes: never
 * throws. When the view cannot be rebuilt it is DELETED rather than left
 * stale, because a stale view is worse than none: it would keep serving a value
 * the pod no longer holds (an erased record's, say) while a reader with no view
 * falls back to the records. The reason comes back as a warning to print.
 */
export async function refreshWellnessDailySeriesAfterWrite(
  podDir: string,
  dek: Buffer | undefined,
): Promise<{ refresh?: DailySeriesRefresh; warning?: string }> {
  const reader = new PodReader(podDir, dek);
  try {
    return { refresh: await refreshWellnessDailySeries(reader) };
  } catch (e: unknown) {
    const why = e instanceof Error ? e.message : String(e);
    let removed = false;
    try {
      const held = readStoredDailySeries(reader);
      if (held.ok && held.value && podPathExists(podDir, held.value.attachment)) removePodFile(podDir, held.value.attachment);
      if (podPathExists(podDir, WELLNESS_DAILY_SERIES_DESCRIPTOR)) {
        removePodFile(podDir, WELLNESS_DAILY_SERIES_DESCRIPTOR);
        removed = true;
      }
    } catch {
      // Reported below: the sentence names the file either way.
    }
    return {
      warning:
        `The stored daily wellness series could not be rebuilt (${why}); ` +
        (removed
          ? `${WELLNESS_DAILY_SERIES_DESCRIPTOR} was removed so no stale series is served. `
          : '') +
        'Run `cascade pod reconcile <pod> --apply` to build it again.',
    };
  }
}
