/**
 * Audit logging for Cascade MCP server.
 *
 * Writes audit entries to a Pod's provenance/audit-log.ttl file
 * to track agent access to health data.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { randomUUID } from 'crypto';

export interface AuditEntry {
  operation: string;
  dataTypes: string[];
  agentId: string;
  recordsAccessed: number;
  timestamp: string;
  podPath?: string;
}

/**
 * Generate a globally unique audit entry ID using crypto.randomUUID().
 * Unlike sequential counters, UUID-based IDs survive server restarts
 * and concurrent sessions without collisions.
 */
function nextAuditId(): string {
  return `audit-${randomUUID()}`;
}

/**
 * Format an audit entry as Cascade Turtle.
 */
function formatAuditEntry(entry: AuditEntry): string {
  const id = nextAuditId();
  const dataTypesStr = entry.dataTypes.map((t) => `"${t}"`).join(' ');

  return `
<#${id}> a cascade:AuditEntry ;
    cascade:timestamp "${entry.timestamp}"^^xsd:dateTime ;
    cascade:operation "${entry.operation}" ;
    cascade:dataTypes (${dataTypesStr}) ;
    cascade:agentId "${entry.agentId}" ;
    cascade:recordsAccessed ${entry.recordsAccessed} .
`;
}

/**
 * Turtle prefixes for the audit log file.
 */
const AUDIT_PREFIXES = `@prefix cascade: <https://ns.cascadeprotocol.org/core/v1#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .

# Cascade Protocol Agent Audit Log
# Generated by cascade serve --mcp
# This file records all agent operations on this Pod.

`;

/**
 * Append an audit entry to a Pod's audit log.
 * Creates the provenance/ directory and audit-log.ttl if they don't exist.
 */
export async function writeAuditEntry(podPath: string, entry: AuditEntry): Promise<void> {
  const provenanceDir = path.join(podPath, 'provenance');
  const auditLogPath = path.join(provenanceDir, 'audit-log.ttl');

  // Ensure provenance directory exists
  await fs.mkdir(provenanceDir, { recursive: true });

  // Check if audit log exists
  let exists = false;
  try {
    await fs.access(auditLogPath);
    exists = true;
  } catch {
    // File doesn't exist yet
  }

  const turtleEntry = formatAuditEntry(entry);

  if (exists) {
    // Append to existing file
    await fs.appendFile(auditLogPath, turtleEntry, 'utf-8');
  } else {
    // Create new file with prefixes
    await fs.writeFile(auditLogPath, AUDIT_PREFIXES + turtleEntry, 'utf-8');
  }
}

/**
 * Create a standard audit entry for a tool invocation.
 */
export function createAuditEntry(
  operation: string,
  dataTypes: string[],
  recordsAccessed: number,
  agentId?: string,
): AuditEntry {
  return {
    operation,
    dataTypes,
    agentId: agentId ?? 'unknown-agent',
    recordsAccessed,
    timestamp: new Date().toISOString(),
  };
}
